apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app1-dp
  labels:
    app: app1
    type: back-end
spec:
  template:
    metadata:
      name: app1-pod
      labels:
        app: app1
        type : back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.17.3
  replicas: 5
  selector:
    matchLabels:
      type: back-end
      app: app1
