apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  app1-rs
  labels:
    app: app1
    type: back-end
spec:
  template: 
    metadata:
      name: app1-pod
      labels:
        app: app1
        type : back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: back-end
      app: app1
